CREATE TABLE IF NOT EXISTS Users (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Username TEXT UNIQUE NOT NULL,
    DateJoined TIMESTAMP DEFAULT (DATETIME('now')) NOT NULL,
    ImageID INTEGER,
    FOREIGN KEY (ImageID) REFERENCES Images(ID)
);